=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/blocks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: blocks.xsd,v 1.3 2007/07/19 16:08:10 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="blocks">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="block" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" />
				<xs:element ref="comment" />
				<xs:element ref="invite" />
				<xs:element ref="class" />
			</xs:sequence>
			<xs:attribute name="auth-required-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="enabled-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="id" use="required" type="xs:NCName" />
			<xs:attribute name="portlet-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="printable-flag" use="required"
				type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string" />
	<xs:element name="description" type="xs:string" />
	<xs:element name="comment" type="xs:string" />
	<xs:element name="invite" type="xs:string" />
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" ref="templateblock-template" />
				<xs:element minOccurs="0" ref="messagesblock-messages" />
				<xs:element minOccurs="0" ref="pagesblock-parameters" />
				<xs:element minOccurs="0" ref="pagesblock-pages" />
			</xs:sequence>
			<xs:attribute name="name" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="messagesblock-messages">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded"
					ref="messagesblock-message" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="messagesblock-message">
		<xs:complexType>
			<xs:attribute name="message-id" use="required"
				type="xs:NCName" />
			<xs:attribute name="order" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="pagesblock-parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded"
					ref="pagesblock-parameter" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pagesblock-parameter">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="pagesblock-pages">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="pagesblock-page" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pagesblock-page">
		<xs:complexType>
			<xs:attribute name="order" use="required" type="xs:integer" />
			<xs:attribute name="page-id" use="required"
				type="xs:NCName" />
			<xs:attribute name="current-icon-id" use="required"
				type="xs:NCName" />
			<xs:attribute name="icon-id" use="required"
				type="xs:NCName" />
		</xs:complexType>
	</xs:element>
	<xs:element name="templateblock-template">
		<xs:complexType>
			<xs:attribute name="template" use="required"
				type="xs:NCName" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/blocks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: blocks.xml,v 1.56 2008/11/19 17:12:05 tdanard Exp $ -->
<blocks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/blocks.xsd">
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-1"
		portlet-flag="Y" printable-flag="N">
		<name>Date Lookup</name>
		<description>To select a date from the calendar</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultCalendarDateLookupBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-10"
		portlet-flag="Y" printable-flag="N">
		<name>Site Content</name>
		<description>
			To search the entire site by content type and by keyword
		</description>
		<comment />
		<invite>
			Select the type of content you want to search for, enter a
			keyword then press GO
		</invite>
		<class
			name="com.corendal.netapps.wiki.blocks.DefaultSiteKeywordSearchFormBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-12"
		portlet-flag="Y" printable-flag="N">
		<name>Log In</name>
		<description>
			To authenticate yourself giving your login and password
		</description>
		<comment />
		<invite>
			<![CDATA[Enter your Windows login and password]]>
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultSignInBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-13"
		portlet-flag="Y" printable-flag="N">
		<name>Log In As</name>
		<description>
			To login using somebody else's credentials
		</description>
		<comment />
		<invite>
			<![CDATA[Enter the login of the person you want to log in as]]>
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultSignInAsBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-14"
		portlet-flag="Y" printable-flag="N">
		<name>Change Password</name>
		<description>
			To modify a password to access this site
		</description>
		<comment />
		<invite>
			For security reasons, you must enter the old password once,
			and the new password twice
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultNativeAccountChangePasswordBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-15"
		portlet-flag="Y" printable-flag="N">
		<name>Change Password</name>
		<description>
			To modify a password to access this site
		</description>
		<comment />
		<invite>
			For security reasons, you must enter the old password once,
			and the new password twice
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultActiveDirectoryAccountChangePasswordBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-16"
		portlet-flag="Y" printable-flag="N">
		<name>Sign Up</name>
		<description>
			To register a new user account giving your contact
			information
		</description>
		<comment>
			This is a required step before authenticating if you have
			never used this site before
		</comment>
		<invite>
			To access this site for the first time, you must create a
			user account by signing up. Rules for login and password are
			displayed on the right side of this screen
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultNativeAccountSignUpBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-18"
		portlet-flag="Y" printable-flag="N">
		<name>Administrative Only</name>
		<description>
			To modify a password to access this site without entering the password currently used
		</description>
		<comment />
		<invite>
			For security reasons, you must enter the new password twice
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultNativeAccountAdministrativeChangePasswordBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-19"
		portlet-flag="Y" printable-flag="N">
		<name>Administrative Only</name>
		<description>
			To modify a password to access this site without entering the password currently used
		</description>
		<comment />
		<invite>
			For security reasons, you must enter the new password twice
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultActiveDirectoryAccountAdministrativeChangePasswordBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-20"
		portlet-flag="Y" printable-flag="N">
		<name>Generate Random Password</name>
		<description>
			To modify a password to access this site without entering
			that new password
		</description>
		<comment />
		<invite>
			Upon submission, the specified account will receive an email
			including the new password to use. This password will be
			generated automatically
		</invite>
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultActiveDirectoryAccountAdministrativeGeneratePasswordBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-23"
		portlet-flag="Y" printable-flag="Y">
		<name>Glossary</name>
		<description>
			Lists the technical terms used in this site
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultTermKeywordSearchFormBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-24"
		portlet-flag="Y" printable-flag="Y">
		<name>Glossary</name>
		<description>
			Lists the technical terms used in this site
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultSiteGlossaryBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-26"
		portlet-flag="Y" printable-flag="Y">
		<name>Glossary</name>
		<description>
			Terms are listed using a default order
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultContextualGlossaryDefaultBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-27"
		portlet-flag="Y" printable-flag="Y">
		<name>Glossary</name>
		<description>Terms are listed alphabetically</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultContextualGlossaryAlphabeticalBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-28"
		portlet-flag="Y" printable-flag="N">
		<name>Site Index</name>
		<description>
			List of all screens accessible to all users in this site
		</description>
		<comment>Some screens may require authentication</comment>
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultScreenKeywordSearchFormBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-29"
		portlet-flag="Y" printable-flag="Y">
		<name>Site Index</name>
		<description>
			List of all screens accessible to all users in this site
		</description>
		<comment>Some screens may require authentication</comment>
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultSiteIndexBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-30"
		portlet-flag="Y" printable-flag="Y">
		<name>My Account</name>
		<description>
			Displays the contact information of your user account
		</description>
		<comment>
			Contact #HelpDeskName# if your account information is
			incorrect
		</comment>
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultMyAccountViewBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-31"
		portlet-flag="Y" printable-flag="N">
		<name>Edit Account</name>
		<description>
			To modify the contact information of your user account
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultMyNativeAccountEditBlock" />
	</block>
	<block auth-required-flag="N" enabled-flag="Y" id="CORE-BLCK-32"
		portlet-flag="Y" printable-flag="Y">
		<name>Site Map</name>
		<description>
			Hierarchical list of all screens accessible to all users in
			this site
		</description>
		<comment>Some screens may require authentication</comment>
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultSiteMapBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-33"
		portlet-flag="Y" printable-flag="N">
		<name>Edit Account</name>
		<description>
			To modify the contact information of your user account
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultMyActiveDirectoryAccountEditBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-34"
		portlet-flag="Y" printable-flag="N">
		<name>Edit Account</name>
		<description>
			To modify the contact information of your user account
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultMyLotusNotesAccountEditBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-35"
		portlet-flag="Y" printable-flag="N">
		<name>New Active Directory Account</name>
		<description>
			To create a new account in Active Directory
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultActiveDirectoryAccountNewBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-36"
		portlet-flag="Y" printable-flag="N">
		<name>New Lotus Notes Account</name>
		<description>
			To create a new account in Lotus Notes
		</description>
		<comment />
		<invite />
		<class
			name="com.corendal.netapps.framework.core.blocks.DefaultLotusNotesAccountNewBlock" />
	</block>
	<block auth-required-flag="Y" enabled-flag="Y" id="CORE-BLCK-37"
		portlet-flag="Y" printable-flag="N">
		<name>New Local Account</name>
		<description>
			To create a new account in the local LDAP database
