=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/entities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: entities.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="entities">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="entity"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zero-name"/>
        <xs:element ref="singular-name"/>
        <xs:element ref="plural-name"/>
        <xs:element ref="xml-singular-name"/>
        <xs:element ref="xml-plural-name"/>
        <xs:element ref="description"/>
        <xs:element ref="comment"/>
        <xs:element ref="no-found"/>
        <xs:element ref="one-found"/>
        <xs:element ref="several-found"/>
        <xs:element ref="factory-class"/>
      </xs:sequence>
      <xs:attribute name="child-priority" use="required" type="xs:integer"/>
      <xs:attribute name="detail-page-id" use="required"/>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="indexed-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="parent-entity-id" use="required"/>
      <xs:attribute name="search-form-page-id" use="required"/>
      <xs:attribute name="search-priority" use="required" type="xs:integer"/>
      <xs:attribute name="search-results-page-id" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="zero-name" type="xs:string"/>
  <xs:element name="singular-name" type="xs:string"/>
  <xs:element name="plural-name" type="xs:string"/>
  <xs:element name="xml-singular-name" type="xs:NCName"/>
  <xs:element name="xml-plural-name" type="xs:NCName"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="no-found" type="xs:string"/>
  <xs:element name="one-found" type="xs:string"/>
  <xs:element name="several-found" type="xs:string"/>
  <xs:element name="factory-class">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: entities.xml,v 1.14 2007/12/26 17:46:13 tdanard Exp $ -->
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/entities.xsd">
	<entity child-priority="0" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-1" indexed-flag="N" parent-entity-id=""
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>page</zero-name>
		<singular-name>page</singular-name>
		<plural-name>pages</plural-name>
		<xml-singular-name>page</xml-singular-name>
		<xml-plural-name>pages</xml-plural-name>
		<description>
			Screen of this site generated by a script
		</description>
		<comment>
			<![CDATA[All pages are defined in the "page" table]]>
		</comment>
		<no-found>No page was found</no-found>
		<one-found>One page was found</one-found>
		<several-found>{1} pages were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.readstandardfactories.DefaultStandardPageFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="HLPD-PAGE-27"
		enabled-flag="Y" id="CORE-ENTY-2" indexed-flag="N" parent-entity-id=""
		search-form-page-id="HLPD-PAGE-1" search-priority="0"
		search-results-page-id="HLPD-PAGE-14">
		<zero-name>user account</zero-name>
		<singular-name>user account</singular-name>
		<plural-name>user accounts</plural-name>
		<xml-singular-name>user</xml-singular-name>
		<xml-plural-name>users</xml-plural-name>
		<description>
			Account associated with a person for this site
		</description>
		<comment />
		<no-found>No user account was found</no-found>
		<one-found>One user account was found</one-found>
		<several-found>{1} user accounts were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardAccountFactory" />
	</entity>
	<entity child-priority="99" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-2-1" indexed-flag="N" parent-entity-id="CORE-ENTY-2"
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>native user account</zero-name>
		<singular-name>native user account</singular-name>
		<plural-name>native user accounts</plural-name>
		<xml-singular-name>native-user</xml-singular-name>
		<xml-plural-name>native-users</xml-plural-name>
		<description>
			Native account associated with a person for this site
		</description>
		<comment />
		<no-found>No native user account was found</no-found>
		<one-found>One native user account was found</one-found>
		<several-found>
			{1} native user accounts were found
		</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardNativeAccountFactory" />
	</entity>
	<entity child-priority="1" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-2-2" indexed-flag="N" parent-entity-id="CORE-ENTY-2"
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>active directory user account</zero-name>
		<singular-name>active directory user account</singular-name>
		<plural-name>active directory user accounts</plural-name>
		<xml-singular-name>active-directory-user</xml-singular-name>
		<xml-plural-name>active-director-users</xml-plural-name>
		<description>
			Active Directory account associated with a person for this
			site
		</description>
		<comment />
		<no-found>No active directory user account was found</no-found>
		<one-found>
			One active directory user account was found
		</one-found>
		<several-found>
			{1} active directory user accounts were found
		</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardActiveDirectoryAccountFactory" />
	</entity>
	<entity child-priority="2" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-2-5" indexed-flag="N" parent-entity-id="CORE-ENTY-2"
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>active directory user account</zero-name>
		<singular-name>active directory user account</singular-name>
		<plural-name>active directory user accounts</plural-name>
		<xml-singular-name>active-directory-user</xml-singular-name>
		<xml-plural-name>active-director-users</xml-plural-name>
		<description>
			Active Directory account associated with a person for this
			site
		</description>
		<comment />
		<no-found>No active directory user account was found</no-found>
		<one-found>
			One active directory user account was found
		</one-found>
		<several-found>
			{1} active directory user accounts were found
		</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardGlobalCatalogAccountFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-3" indexed-flag="N" parent-entity-id=""
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>field</zero-name>
		<singular-name>field</singular-name>
		<plural-name>fields</plural-name>
		<xml-singular-name>field</xml-singular-name>
		<xml-plural-name>fields</xml-plural-name>
		<description>Input zone for entry or search forms</description>
		<comment />
		<no-found>No field was found</no-found>
		<one-found>One field was found</one-found>
		<several-found>{1} fields were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.readstandardfactories.DefaultStandardFieldFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="ADMN-PAGE-87"
		enabled-flag="Y" id="CORE-ENTY-31" indexed-flag="N"
		parent-entity-id="" search-form-page-id="" search-priority="0"
		search-results-page-id="ADMN-PAGE-74">
		<zero-name>error log</zero-name>
		<singular-name>error log</singular-name>
		<plural-name>error logs</plural-name>
		<xml-singular-name>error-log</xml-singular-name>
		<xml-plural-name>error-logs</xml-plural-name>
		<description>An error log</description>
		<comment />
		<no-found>No error log was found</no-found>
		<one-found>One error log was found</one-found>
		<several-found>{1} error logs were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardErrorLogFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="ADMN-PAGE-81"
		enabled-flag="Y" id="CORE-ENTY-32" indexed-flag="N"
		parent-entity-id="" search-form-page-id="" search-priority="0"
		search-results-page-id="ADMN-PAGE-82">
		<zero-name>file</zero-name>
		<singular-name>file</singular-name>
		<plural-name>files</plural-name>
		<xml-singular-name>file</xml-singular-name>
		<xml-plural-name>files</xml-plural-name>
		<description>A file</description>
		<comment />
		<no-found>No file was found</no-found>
		<one-found>One file was found</one-found>
		<several-found>{1} files were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardFileFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="ADMN-PAGE-88"
		enabled-flag="Y" id="CORE-ENTY-33" indexed-flag="N"
		parent-entity-id="" search-form-page-id="ADMN-PAGE-68"
		search-priority="0" search-results-page-id="">
		<zero-name>email</zero-name>
		<singular-name>email</singular-name>
		<plural-name>emails</plural-name>
		<xml-singular-name>email</xml-singular-name>
		<xml-plural-name>emails</xml-plural-name>
		<description>An email id</description>
		<comment />
		<no-found>No email was found</no-found>
		<one-found>One email was found</one-found>
		<several-found>{1} emails were found</several-found>
		<factory-class
			name="com.corendal.netapps.framework.core.writestandardfactories.DefaultStandardEmailFactory" />
	</entity>
	<entity child-priority="0" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-38" indexed-flag="N" parent-entity-id=""
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>proxy</zero-name>
		<singular-name>proxy</singular-name>
		<plural-name>proxies</plural-name>
		<xml-singular-name>proxy</xml-singular-name>
		<xml-plural-name>proxies</xml-plural-name>
		<description>
			Grant given by a user to another user, allowing identical
			access rights in this application
		</description>
		<comment />
		<no-found>No proxy was found</no-found>
		<one-found>One proxy was found</one-found>
		<several-found>{1} proxies were found</several-found>
		<factory-class name="" />
	</entity>
	<entity child-priority="0" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-39" indexed-flag="N" parent-entity-id=""
		search-form-page-id="" search-priority="0"
		search-results-page-id="">
		<zero-name>preference</zero-name>
		<singular-name>preference</singular-name>
		<plural-name>preferences</plural-name>
		<xml-singular-name>preference</xml-singular-name>
		<xml-plural-name>preferences</xml-plural-name>
		<description>
			Customization of the behavior of this site for a particular
			account
		</description>
		<comment />
		<no-found>No preference was found</no-found>
		<one-found>One preference was found</one-found>
		<several-found>{1} preferences were found</several-found>
		<factory-class name="" />
	</entity>
	<entity child-priority="0" detail-page-id="" enabled-flag="Y"
		id="CORE-ENTY-4" indexed-flag="N" parent-entity-id=""
		search-form-page-id="CORE-PAGE-16" search-priority="0"
		search-results-page-id="CORE-PAGE-16">
		<zero-name>term</zero-name>
		<singular-name>term</singular-name>
		<plural-name>terms</plural-name>
		<xml-singular-name>term</xml-singular-name>
		<xml-plural-name>terms</xml-plural-name>
		<description>
			Word or expression that has a precise meaning in this site
		</description>
		<comment />
		<no-found>No term was found</no-found>
		<one-found>One term was found</one-found>
		<several-found>{1} terms were found</several-found>
		<factory-class name="" />
	</entity>
	<entity child-priority="0" detail-page-id="ADMN-PAGE-83"
