=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/fields.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: fields.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="field"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contextual-name"/>
        <xs:element ref="full-name"/>
        <xs:element ref="xml-contextual-name"/>
        <xs:element ref="xml-full-name"/>
        <xs:element ref="vcard-name"/>
        <xs:element ref="preferred-name"/>
        <xs:element ref="description"/>
        <xs:element ref="comment"/>
        <xs:element ref="access-key"/>
      </xs:sequence>
      <xs:attribute name="display-entry-size" use="required" type="xs:integer"/>
      <xs:attribute name="display-search-size" use="required" type="xs:integer"/>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="entity-id" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="indexed-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="max-entry-size" use="required" type="xs:integer"/>
      <xs:attribute name="max-search-size" use="required" type="xs:integer"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="contextual-name" type="xs:string"/>
  <xs:element name="full-name" type="xs:string"/>
  <xs:element name="xml-contextual-name" type="xs:NCName"/>
  <xs:element name="xml-full-name" type="xs:NCName"/>
  <xs:element name="vcard-name">
    <xs:complexType/>
  </xs:element>
  <xs:element name="preferred-name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="access-key" type="xs:string"/>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/fields.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: fields.xml,v 1.32 2008/11/04 22:43:27 tdanard Exp $ -->
<fields xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/fields.xsd">
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-8" id="CORE-FILD-1"
		indexed-flag="N" max-entry-size="100" max-search-size="100"
		type="VARCHAR">
		<contextual-name>Language</contextual-name>
		<full-name>Language</full-name>
		<xml-contextual-name>language</xml-contextual-name>
		<xml-full-name>language</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Customization of this site based upon your geographical or
			cultural region
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-15"
		indexed-flag="N" max-entry-size="255" max-search-size="255"
		type="VARCHAR">
		<contextual-name>Login</contextual-name>
		<full-name>User Account Login</full-name>
		<xml-contextual-name>login</xml-contextual-name>
		<xml-full-name>account-login</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Unique identifier of a user account for this site
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-16"
		indexed-flag="N" max-entry-size="20" max-search-size="20"
		type="VARCHAR">
		<contextual-name>Password</contextual-name>
		<full-name>User Account Password</full-name>
		<xml-contextual-name>password</xml-contextual-name>
		<xml-full-name>account-password</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Secret sequence of characters required for access to this
			site
		</description>
		<comment>
			A password is personal, and must be at least 6 characters
			long to be valid
		</comment>
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-17"
		indexed-flag="N" max-entry-size="20" max-search-size="20"
		type="VARCHAR">
		<contextual-name>Enable auto log in</contextual-name>
		<full-name>User Account Enable auto log in</full-name>
		<xml-contextual-name>auto-sign-in</xml-contextual-name>
		<xml-full-name>account-auto-sign-in</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Automatically signs you in next time you connect to this
			server
		</description>
		<comment>
			This option should be used only if you are not using a
			public computer
		</comment>
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-18"
		indexed-flag="N" max-entry-size="20" max-search-size="20"
		type="VARCHAR">
		<contextual-name>Old Password</contextual-name>
		<full-name>Old User Account Password</full-name>
		<xml-contextual-name>old-password</xml-contextual-name>
		<xml-full-name>account-old-password</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Current secret sequence of characters required for access to
			this site
		</description>
		<comment>
			A password is personal, and must be at least 6 characters
			long to be valid
		</comment>
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-19"
		indexed-flag="N" max-entry-size="20" max-search-size="20"
		type="VARCHAR">
		<contextual-name>New Password</contextual-name>
		<full-name>New User Account Password</full-name>
		<xml-contextual-name>new-password</xml-contextual-name>
		<xml-full-name>account-new-password</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			New secret sequence of characters required for access to
			this site
		</description>
		<comment>
			A password is personal, and must be at least 6 characters
			long to be valid
		</comment>
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-8" id="CORE-FILD-2"
		indexed-flag="N" max-entry-size="100" max-search-size="100"
		type="VARCHAR">
		<contextual-name />
		<full-name />
		<xml-contextual-name>empty</xml-contextual-name>
		<xml-full-name>empty</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description />
		<comment />
		<access-key />
	</field>
	<field display-entry-size="20" display-search-size="20"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-20"
		indexed-flag="N" max-entry-size="20" max-search-size="20"
		type="VARCHAR">
		<contextual-name>Repeat New Password</contextual-name>
		<full-name>Repeat New User Account Password</full-name>
		<xml-contextual-name>new-password</xml-contextual-name>
		<xml-full-name>account-new-password</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			New secret sequence of characters required for access to
			this site
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="30" display-search-size="30"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-21"
		indexed-flag="N" max-entry-size="30" max-search-size="30"
		type="VARCHAR">
		<contextual-name>First Name</contextual-name>
		<full-name>User Account First Name</full-name>
		<xml-contextual-name>first-name</xml-contextual-name>
		<xml-full-name>account-first-name</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			The name that stands first in a full name
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-8" id="CORE-FILD-213"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Name</contextual-name>
		<full-name>Match Name</full-name>
		<xml-contextual-name>name</xml-contextual-name>
		<xml-full-name>match-name</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>Name of the match</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-8" id="CORE-FILD-214"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Description</contextual-name>
		<full-name>Match Description</full-name>
		<xml-contextual-name>description</xml-contextual-name>
		<xml-full-name>match-description</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Detailed description or preview of the match
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-4" id="CORE-FILD-219"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Name</contextual-name>
		<full-name>Term Name</full-name>
		<xml-contextual-name>name</xml-contextual-name>
		<xml-full-name>term-name</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>Word or expression used</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="30" display-search-size="30"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-22"
		indexed-flag="N" max-entry-size="30" max-search-size="30"
		type="VARCHAR">
		<contextual-name>Last Name</contextual-name>
		<full-name>User Account Last Name</full-name>
		<xml-contextual-name>last-name</xml-contextual-name>
		<xml-full-name>account-last-name</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			The name that stands last in a full name
		</description>
		<comment>The last name is also called surname</comment>
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-4" id="CORE-FILD-220"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Description</contextual-name>
		<full-name>Term Description</full-name>
		<xml-contextual-name>description</xml-contextual-name>
		<xml-full-name>term-description</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Detailed explanation of a word or expression
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-6" id="CORE-FILD-226"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Name</contextual-name>
		<full-name>Screen Name</full-name>
		<xml-contextual-name>name</xml-contextual-name>
		<xml-full-name>screen-name</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Name of the screen, as displayed in the header
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="0" display-search-size="0"
		enabled-flag="Y" entity-id="CORE-ENTY-6" id="CORE-FILD-227"
		indexed-flag="N" max-entry-size="0" max-search-size="0"
		type="VARCHAR">
		<contextual-name>Description</contextual-name>
		<full-name>Screen Description</full-name>
		<xml-contextual-name>description</xml-contextual-name>
		<xml-full-name>screen-description</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Detailed explanation of the function of the screen
		</description>
		<comment />
		<access-key />
	</field>
	<field display-entry-size="30" display-search-size="30"
		enabled-flag="Y" entity-id="CORE-ENTY-2" id="CORE-FILD-23"
		indexed-flag="N" max-entry-size="100" max-search-size="100"
		type="VARCHAR">
		<contextual-name>Email Address</contextual-name>
		<full-name>User Account Email Address</full-name>
		<xml-contextual-name>email-address</xml-contextual-name>
		<xml-full-name>account-email-address</xml-full-name>
		<vcard-name />
		<preferred-name />
		<description>
			Mailbox used to send and receive electronic messages
		</description>
