=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/grouptypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: grouptypes.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="grouptypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="grouptype"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="grouptype">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="comment"/>
      </xs:sequence>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="order" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:NCName"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/grouptypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: grouptypes.xml,v 1.3 2006/07/17 02:23:36 tdanard Exp $ -->
<grouptypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/grouptypes.xsd">
	<grouptype enabled-flag="Y" id="HLPD-GRPT-1" order="1">
		<name>Public</name>
		<description>
			A user group is public when displayed by default in lookups
		</description>
		<comment />
	</grouptype>
	<grouptype enabled-flag="Y" id="HLPD-GRPT-2" order="2">
		<name>Personal</name>
		<description>
			A user group is personal when not displayed by default in
			lookups
		</description>
		<comment>
			Any user has access to the list of members of a personal
			group
		</comment>
	</grouptype>
</grouptypes>
