=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/icons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="icons">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="icon"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="icon">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="title"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="description"/>
          <xs:element ref="extension"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="height" use="required" type="xs:integer"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="width" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="extension">
    <xs:complexType>
      <xs:attribute name="direct-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="secure-flag" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/icons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: icons.xml,v 1.5 2005/11/22 04:14:52 tdanard Exp $ -->
<icons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/icons.xsd">
	<icon enabled-flag="Y" height="12" id="CORE-ICON-1" width="23">
		<name>/flag/newresource.png</name>
		<title />
		<description>Indicates a resource is new</description>
	</icon>
	<icon enabled-flag="Y" height="12" id="CORE-ICON-2" width="54">
		<name>/flag/updatedresource.png</name>
		<title />
		<description>
			Indicates a resource has been recently updated
		</description>
	</icon>
	<icon enabled-flag="Y" height="16" id="CORE-ICON-3" width="16">
		<name>/format/formathtml.png</name>
		<title>Screen</title>
		<description />
	</icon>
	<icon enabled-flag="Y" height="16" id="CORE-ICON-6" width="16">
		<name>/format/currentformathtml.png</name>
		<title>Screen</title>
		<description />
	</icon>
	<icon enabled-flag="Y" height="13" id="CORE-ICON-9" width="9">
		<name>/framework/ascending.png</name>
		<title />
		<description>
			Displayed in table headers for ascending columns
		</description>
	</icon>
	<icon enabled-flag="Y" height="13" id="CORE-ICON-10" width="9">
		<name>/framework/descending.png</name>
		<title />
		<description>
			Displayed in table headers for descending columns
		</description>
	</icon>
	<icon enabled-flag="Y" height="24" id="CORE-ICON-11" width="24">
		<name>/style/curve-ltr.jpg</name>
		<title />
		<description>
			Displayed in the standard header before the portal name
		</description>
	</icon>
	<icon enabled-flag="Y" height="24" id="CORE-ICON-12" width="24">
		<name>/style/curve-rtl.jpg</name>
		<title />
		<description>
			Displayed in the standard header before the portal name
		</description>
	</icon>
	<icon enabled-flag="Y" height="32" id="CORE-ICON-13" width="32">
		<name>/framework/spacer.png</name>
		<title />
		<description>Used to create spaces</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-14" width="10">
		<name>/menu/menumiddlebottom.png</name>
		<title />
		<description>
			Displayed in the main menu under the title of a menu item,
			if this item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="7" id="CORE-ICON-15" width="10">
		<name>/menu/menumiddletop.png</name>
		<title />
		<description>
			Displayed in the main menu over the title of a menu item, if
			this item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-16" width="10">
		<name>/menu/menuselectedmiddlebottom.png</name>
		<title />
		<description>
			Displayed in the main menu under the title of a menu item,
			if this item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="7" id="CORE-ICON-17" width="10">
		<name>/menu/menuselectedmiddletop.png</name>
		<title />
		<description>
			Displayed in the main menu over the title of a menu item, if
			this item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-18" width="32">
		<name>/menu/menufirst-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu before the first menu item, if
			this item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-19" width="32">
		<name>/menu/menulast-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu after the last menu item, if this
			item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-20" width="32">
		<name>/menu/menuright-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if the
			previous and next items are not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-21" width="32">
		<name>/menu/menuselectedfirst-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu before the first menu item, if
			this item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-22" width="32">
		<name>/menu/menuselectedlast-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu in case the last menu item is
			selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-23" width="32">
		<name>/menu/menuselectedleft-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if this item
			is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-24" width="32">
		<name>/menu/menuselectedright-ltr.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if the
			previous item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-25" width="32">
		<name>/menu/menufirst-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu before the first menu item, if
			this item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-26" width="32">
		<name>/menu/menulast-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu after the last menu item, if this
			item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-27" width="32">
		<name>/menu/menuright-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if the
			previous and next items are not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="23" id="CORE-ICON-28" width="15">
		<name>/menu/menuselectedfirst-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu before the first menu item, if
			this item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-29" width="32">
		<name>/menu/menuselectedlast-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu in case the last menu item is
			selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-30" width="32">
		<name>/menu/menuselectedleft-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if this item
			is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="22" id="CORE-ICON-31" width="32">
		<name>/menu/menuselectedright-rtl.png</name>
		<title />
		<description>
			Displayed in the main menu after a menu item, if the
			previous item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-32" width="10">
		<name>/tab/whitetabselectedmiddlebottom.png</name>
		<title />
		<description>
			Displayed in a tab under the title of a tab item, if this
			item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="7" id="CORE-ICON-33" width="8">
		<name>/tab/whitetabselectedmiddletop.png</name>
		<title />
		<description>
			Displayed in a tab over the title of a tab item, if this
			item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-34" width="10">
		<name>/tab/whitetabmiddlebottom.png</name>
		<title />
		<description>
			Displayed in a tab under the title of a tab item, if this
			item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="7" id="CORE-ICON-35" width="8">
		<name>/tab/whitetabmiddletop.png</name>
		<title />
		<description>
			Displayed in a tab over the title of a tab item, if this
			item is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-36" width="10">
		<name>/tab/whitetabbottom.png</name>
		<title />
		<description>
			Displayed at the bottom tab, drawing the bottom line
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-37" width="9">
		<name>/tab/whitetablast-ltr.png</name>
		<title />
		<description>
			Displayed in a tab after the last tab item, if this item is
			not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-38" width="15">
		<name>/tab/whitetabright-ltr.png</name>
		<title />
		<description>
			Displayed in a tab after a tab item, if the previous and
			next items are not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-39" width="9">
		<name>/tab/whitetabselectedfirst-ltr.png</name>
		<title />
		<description>
			Displayed in a tab before the first tab item, if this item
			is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-40" width="9">
		<name>/tab/whitetabselectedlast-ltr.png</name>
		<title />
		<description>
			Displayed in a tab in case the last tab item is selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-41" width="15">
		<name>/tab/whitetabselectedleft-ltr.png</name>
		<title />
		<description>
			Displayed in a tab after a tab item, if this item is
			selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-42" width="15">
		<name>/tab/whitetabselectedright-ltr.png</name>
		<title />
		<description>
			Displayed in a tab after a tab item, if the previous item is
			selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="28" id="CORE-ICON-43" width="9">
		<name>/tab/whitetabfirst-ltr.png</name>
		<title />
		<description>
			Displayed in a tab before the first tab item, if this item
			is not selected
		</description>
	</icon>
	<icon enabled-flag="Y" height="9" id="CORE-ICON-44" width="9">
		<name>/tab/whitetabbottomleftcorner-ltr.png</name>
		<title />
		<description>
			Displayed at the bottom left of a tab, drawing the left
			corner
		</description>
	</icon>
	<icon enabled-flag="Y" height="9" id="CORE-ICON-45" width="9">
		<name>/tab/whitetabbottomrightcorner-ltr.png</name>
		<title />
		<description>
			Displayed at the bottom right of a tab, drawing the right
			corner
		</description>
	</icon>
	<icon enabled-flag="Y" height="3" id="CORE-ICON-46" width="9">
		<name>/tab/whitetabtoprightcorner1-ltr.png</name>
		<title />
		<description>
