=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/ldapsourcenode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: ldapsourcenode.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ldapsource-node">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dn"/>
        <xs:element minOccurs="0" ref="preferred-domain"/>
        <xs:element ref="object-class"/>
        <xs:element minOccurs="0" ref="object-category"/>
        <xs:element maxOccurs="unbounded" ref="attribute"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dn" type="xs:string"/>
  <xs:element name="preferred-domain" type="xs:string"/>
  <xs:element name="object-class" type="xs:NCName"/>
  <xs:element name="object-category" type="xs:string"/>
  <xs:element name="attribute">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/ldapsource/globalcatalog/nodes/Account.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Account.xml,v 1.5 2008/10/16 21:50:35 tdanard Exp $ -->
<ldapsource-node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/ldapsourcenode.xsd">
	<dn>dc=mycompany,dc=com</dn>
	<preferred-domain>mydomain.mycompany.com</preferred-domain>
	<object-class>user</object-class>
	<object-category />
	<attribute name="UID">userPrincipalName</attribute>
	<attribute name="UserAccountControl">userAccountControl</attribute>
	<attribute name="SAMAccountName">sAMAccountName</attribute>
	<attribute name="DisplayName">cn</attribute>
	<attribute name="PreferredDisplayName">displayName</attribute>
	<attribute name="FirstName">givenName</attribute>
	<attribute name="LastName">sn</attribute>
	<attribute name="LandlineNumber">telephoneNumber</attribute>
	<attribute name="MobileNumber">mobile</attribute>
	<attribute name="FaxNumber">facsimileTelephoneNumber</attribute>
	<attribute name="AlternativeNumber">ipPhone</attribute>
	<attribute name="HomeNumber">homePhone</attribute>
	<attribute name="MiddleInitial">initials</attribute>
	<attribute name="EmailAddress">mail</attribute>
	<attribute name="PagerNumber">pager</attribute>
	<attribute name="Delivery">physicalDeliveryOfficeName</attribute>
	<attribute name="Department">department</attribute>
	<attribute name="Address">streetAddress</attribute>
	<attribute name="ZipCode">postalCode</attribute>
	<attribute name="City">l</attribute>
	<attribute name="State">st</attribute>
	<attribute name="Country">co</attribute>
	<attribute name="CountryCode">c</attribute>
	<attribute name="Company">company</attribute>
	<attribute name="DistinguishedName">distinguishedName</attribute>
	<attribute name="MemberOf">memberOf</attribute>
	<attribute name="Description">description</attribute>
	<attribute name="DriveName">info</attribute>
	<attribute name="Photo">thumbnailPhoto</attribute>
	<attribute name="Manager">manager</attribute>
	<attribute name="JobTitle">title</attribute>
	<attribute name="EmployeeId">employeeID</attribute>
	<attribute name="EmployeeType">employeeType</attribute>
	<attribute name="ProxyAddress">proxyAddresses</attribute>
	<attribute name="LegacyExchangeDN">legacyExchangeDN</attribute>
	<attribute name="ShowInAddressBook">showInAddressBook</attribute>
	<attribute name="TargetAddress">targetAddress</attribute>
	<attribute name="Secretary">secretary</attribute>
	<attribute name="TelephoneAssistant">telephoneAssistant</attribute>
</ldapsource-node>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/ldapsource/activedirectory/nodes/Group.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Group.xml,v 1.4 2007/01/16 18:41:20 tdanard Exp $ -->
<ldapsource-node xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/ldapsourcenode.xsd">
	<dn>dc=mydomain,dc=mycompany,dc=com</dn>
	<object-class>group</object-class>
	<object-category />
	<attribute name="GID">cn</attribute>
	<attribute name="DisplayName">cn</attribute>
	<attribute name="DistinguishedName">distinguishedName</attribute>
	<attribute name="Member">member</attribute>
	<attribute name="Description">description</attribute>
	<attribute name="Manager">managedBy</attribute>
	<attribute name="GroupType">groupType</attribute>
</ldapsource-node>
