=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: messages.xsd,v 1.3 2007/06/05 23:41:11 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="messages">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="message"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="message">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contents"/>
      </xs:sequence>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="contents">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="content"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="content">
    <xs:complexType mixed="true">
      <xs:attribute name="extension-id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../../schemas/messages.xsd">
	<message enabled-flag="Y" id="CORE-MESG-1" type="DSP">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Copyright 2005 #CompanyName#. All rights reserved
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-10" type="DSP">
		<contents>
			<content extension-id="CORE-EXTN-1">Page #</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1001" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				One or several mandatory fields are not entered. The
				missing fields are listed below
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1002" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				<![CDATA["{1}" is missing]]>
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1003" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The login entered does not match any known user account.
				Logins are case-sensitive. Please enter a valid login
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1004" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The password entered is not valid for this login.
				Passwords are case-sensitive. Please enter a valid
				password
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1005" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				This user account has
				expired. Access cannot be granted. Please contact
				#HelpDeskName#
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1006" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The password proposed does not meet all required rules.
				These rules are displayed on the right side of the
				screen. Please use a valid password
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1007" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The new password must be entered twice, and the two
				entries must be identical
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1008" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The login is already in use. Please choose another login
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1009" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The login proposed does not meet all required rules.
				These rules are displayed on the right side of the
				screen. Please use a valid login
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1010" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The email address is not valid. Please enter a valid
				email address
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1011" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Your user account has been created. Please log in
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1013" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				This user account has been updated
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1014" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You have been authenticated as {1}
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1015" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The password of this user account has been changed
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1016" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You are required to log in for access
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1017" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Your request could not be completed
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1018" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				<![CDATA[The following error was detected: "{1}"]]>
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1019" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">{1}</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1020" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				{1}. Please refine your search criteria
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1021" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You must fill the form before submitting it
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1022" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				This export will take around {1}, press OK to continue
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1023" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You have been signed out
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1024" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You must select at least one type of content
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1025" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You cannot upload files larger than {1} Megabyte(s)
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1026" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				<![CDATA[The format used for the "{1}" date is incorrect. Please use the DDMMMYYYY format. Example: 03SEP2004]]>
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1027" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				<![CDATA[The interval you entered for the "{1}" date is incorrect. The lower boundary must precede the upper boundary]]>
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1028" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				<![CDATA["{1}" is a common word and was not included in your search]]>
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1029" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Try alternate spellings or similar words, such as {1}
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1030" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Wildcards are not supported. Please use other search
				criteria
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1031" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You do not have sufficient credentials to edit this
				account
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1032" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The system has detected that you have submitted this
				form twice. This can be caused by clicking a button
				twice instead of once. Please submit this form again if
				you did mean to submit this form twice
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1033" type="INF">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You must be authenticated to have access to this feature
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1034" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				Some information used by this form has been modified
				while you were filling it out. Please try again
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1035" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You do not have sufficient credentials to create a new
				account
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1036" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The user account {1} has been created. You MUST also
				create an account in Lotus Notes
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1037" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				No active directory account was found matching the
				template name you entered. Please use the lookup
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1038" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				More than one active directory account matched the
				template name you entered. Please use the lookup
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1039" type="VLD">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You have been authenticated as {1}. To use this site,
				you must read and comply with the {2}
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1040" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The name "{1}" is already used in the "{2}"
				organizational unit
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1041" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				The supervisor must be an Active Directory user account
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1042" type="ERR">
		<contents>
			<content extension-id="CORE-EXTN-1">
				You must select a building when searching by room
			</content>
		</contents>
	</message>
	<message enabled-flag="Y" id="CORE-MESG-1043" type="ERR">
		<contents>
