=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/pages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: pages.xsd,v 1.2 2007/07/19 21:32:02 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pages">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="page"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="page">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="comment"/>
        <xs:element ref="access-key"/>
        <xs:element minOccurs="0" ref="urls"/>
        <xs:element ref="class"/>
      </xs:sequence>
      <xs:attribute name="app-id" use="required"/>
      <xs:attribute name="auth-required-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="indexed-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="menu-id" use="required" type="xs:NCName"/>
      <xs:attribute name="parent-page-id" use="required"/>
      <xs:attribute name="servlet-id" use="required"/>
      <xs:attribute name="template-type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="access-key" type="xs:string"/>
  <xs:element name="urls">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="url"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="url">
    <xs:complexType>
      <xs:attribute name="absolute-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="base" use="required"/>
      <xs:attribute name="default-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="directory" use="required"/>
      <xs:attribute name="redirect-flag" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="class">
    <xs:complexType>
      <xs:sequence>
		<xs:element minOccurs="0" ref="templatepage-template" />
        <xs:element minOccurs="0" ref="blockspage-blocks"/>
      </xs:sequence>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="blockspage-blocks">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="blockspage-block"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="blockspage-block">
    <xs:complexType>
      <xs:attribute name="block-id" use="required" type="xs:NCName"/>
      <xs:attribute name="display-header-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="horizontal-order" use="required" type="xs:integer"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="vertical-order" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
	<xs:element name="templatepage-template">
		<xs:complexType>
			<xs:attribute name="template" use="required"
				type="xs:NCName" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/pages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: pages.xml,v 1.36 2008/02/03 20:31:45 tdanard Exp $ -->
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/pages.xsd">
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-1" indexed-flag="Y" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Home Page</name>
		<description>Entry point of this site</description>
		<comment>
			This application is dedicated to technical documentation
			consultation and collaborative writing
		</comment>
		<access-key>1</access-key>
		<urls>
			<url absolute-flag="N" base="/" default-flag="Y"
				directory="/home" redirect-flag="Y" />
			<url absolute-flag="N" base="/" default-flag="N"
				directory="/0" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.wiki.pages.DefaultHomeStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="WIKI-BLCK-16"
					display-header-flag="Y" horizontal-order="1" type="LARGE"
					vertical-order="1" />
				<blockspage-block block-id="WIKI-BLCK-38"
					display-header-flag="Y" horizontal-order="2" type="LARGE"
					vertical-order="1" />
				<blockspage-block block-id="WIKI-BLCK-115"
					display-header-flag="Y" horizontal-order="3" type="LARGE"
					vertical-order="1" />
				<blockspage-block block-id="WIKI-BLCK-2"
					display-header-flag="Y" horizontal-order="1" type="LARGE"
					vertical-order="2" />
				<blockspage-block block-id="WIKI-BLCK-21"
					display-header-flag="Y" horizontal-order="1" type="SMALL"
					vertical-order="1" />
				<blockspage-block block-id="WIKI-BLCK-22"
					display-header-flag="N" horizontal-order="1" type="SMALL"
					vertical-order="2" />
				<blockspage-block block-id="WIKI-BLCK-68"
					display-header-flag="N" horizontal-order="1" type="SMALL"
					vertical-order="3" />
				<blockspage-block block-id="WIKI-BLCK-69"
					display-header-flag="N" horizontal-order="1" type="SMALL"
					vertical-order="4" />
				<blockspage-block block-id="WIKI-BLCK-3"
					display-header-flag="Y" horizontal-order="1" type="SMALL"
					vertical-order="5" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-10" indexed-flag="Y" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Basic Search</name>
		<description>
			To search the entire site by content type and by keyword
		</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/basicsearchform"
				default-flag="Y" directory="/search" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="CORE-BLCK-10"
					display-header-flag="Y" horizontal-order="1" type="LARGE"
					vertical-order="1" />
				<blockspage-block block-id="WIKI-BLCK-25"
					display-header-flag="Y" horizontal-order="1" type="SMALL"
					vertical-order="1" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-11" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Log In / Sign Up</name>
		<description>To authenticate yourself</description>
		<comment>
			If you have never used this site before, you need to create
			a user account by signing up
		</comment>
		<access-key />
		<urls>
			<url absolute-flag="N" base="/loginsignup" default-flag="Y"
				directory="/customize" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-12" indexed-flag="N" menu-id="CORE-MENU-2"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="FLOATING">
		<name>View Glossary</name>
		<description>
			Defines each field or technical term used in this screen
		</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/defaultglossary"
				default-flag="Y" directory="/help" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="CORE-BLCK-26"
					display-header-flag="N" horizontal-order="1" type="LARGE"
					vertical-order="1" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-13" indexed-flag="N" menu-id="CORE-MENU-2"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="FLOATING">
		<name>View Glossary</name>
		<description>
			Defines each field or technical term used in this screen
		</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/alphabeticalglossary"
				default-flag="Y" directory="/help" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="CORE-BLCK-27"
					display-header-flag="N" horizontal-order="1" type="LARGE"
					vertical-order="1" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-14" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Sign Out</name>
		<description>To end your session</description>
		<comment>
			Your authentication will be lost after signing out. Sign
			back in to return to this site
		</comment>
		<access-key>7</access-key>
		<urls>
			<url absolute-flag="N" base="/signout" default-flag="Y"
				directory="/customize" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardSignOutPage" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-15" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Help</name>
		<description>To get help about this site</description>
		<comment />
		<access-key>6</access-key>
		<urls>
			<url absolute-flag="N" base="/" default-flag="Y"
				directory="/help" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardTabRedirectPage" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-16" indexed-flag="Y" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Glossary</name>
		<description>
			Definition of most technical terms used in this site
		</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/glossary" default-flag="Y"
				directory="/help" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="CORE-BLCK-24"
					display-header-flag="Y" horizontal-order="1" type="LARGE"
					vertical-order="1" />
				<blockspage-block block-id="CORE-BLCK-23"
					display-header-flag="Y" horizontal-order="1" type="SMALL"
					vertical-order="1" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-18" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name />
		<description />
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/keepsessionalive"
				default-flag="Y" directory="/customize" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardKeepSessionAlivePage" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-19" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name>Forbidden</name>
		<description>
			Indicates that you have been denied access to the screen
			requested
		</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/forbidden" default-flag="Y"
				directory="/error" redirect-flag="N" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage">
			<blockspage-blocks>
				<blockspage-block block-id="WIKI-BLCK-76"
					display-header-flag="Y" horizontal-order="1" type="LARGE"
					vertical-order="1" />
			</blockspage-blocks>
		</class>
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-2" indexed-flag="Y" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="" template-type="STANDARD">
		<name>www.mycompany.com</name>
		<description>My Company's Home Page</description>
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="Y" base="/" default-flag="Y"
				directory="http://www.mycompany.com" redirect-flag="N" />
		</urls>
		<class name="" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-201" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="CORE-SERV-1" template-type="STANDARD">
		<name />
		<description />
		<comment />
		<access-key />
		<urls>
			<url absolute-flag="N" base="/changepassword"
				default-flag="Y" directory="/customize" redirect-flag="Y" />
		</urls>
		<class
			name="com.corendal.netapps.framework.core.pages.DefaultStandardLargeFirstBlocksPage" />
	</page>
	<page app-id="" auth-required-flag="N" enabled-flag="Y"
		id="CORE-PAGE-202" indexed-flag="N" menu-id="CORE-MENU-1"
		parent-page-id="" servlet-id="" template-type="STANDARD">
		<name>Reset Password</name>
		<description>
			To gain access to this site when you have forgotten your
			password
		</description>
		<comment />
		<access-key />
		<class name="" />
	</page>
