=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/proxyreadpref.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: proxyreadpref.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="proxyreadprefs">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="proxyreadpref"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="proxyreadpref">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="comment"/>
      </xs:sequence>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="order" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description">
    <xs:complexType/>
  </xs:element>
  <xs:element name="comment">
    <xs:complexType/>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/proxyreadprefs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: proxyreadprefs.xml,v 1.3 2006/07/17 02:23:36 tdanard Exp $ -->
<proxyreadprefs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/proxyreadpref.xsd">
	<proxyreadpref enabled-flag="Y" id="CORE-PRPF-1" order="1">
		<name>
			Do NOT let this grantee access resources I can view but not
			edit
		</name>
		<description />
		<comment />
	</proxyreadpref>
	<proxyreadpref enabled-flag="Y" id="CORE-PRPF-2" order="2">
		<name>
			Let this grantee access resources I can view but not edit
		</name>
		<description />
		<comment />
	</proxyreadpref>
</proxyreadprefs>
