=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/roles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: roles.xsd,v 1.4 2007/11/16 20:51:42 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="roles">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="role" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="role">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" />
				<xs:element ref="description" />
				<xs:element ref="comment" />
			</xs:sequence>
			<xs:attribute name="queued-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="enabled-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="file-standalone-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="ldap-control-standalone-flag"
				use="required" type="xs:NCName" />
			<xs:attribute name="account-standalone-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="group-standalone-flag" use="required"
				type="xs:NCName" />
			<xs:attribute name="id" use="required" type="xs:NCName" />
			<xs:attribute name="order" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string" />
	<xs:element name="description" type="xs:string" />
	<xs:element name="comment" type="xs:string" />
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/roles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: roles.xml,v 1.10 2008/11/19 17:12:05 tdanard Exp $ -->
<roles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/roles.xsd">
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="WIKI-ROLE-1" order="4"
		queued-flag="N">
		<name>Editor</name>
		<description>
			Person responsible for the content of an article and all
			associated content
		</description>
		<comment>
			This person must ensure all content is ready for
			publication, including conformity with standards. The editor
			must also ensure that the content is relevant and up-to-date
		</comment>
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="WIKI-ROLE-2" order="5"
		queued-flag="N">
		<name>Author</name>
		<description>
			Person who originated the content but not necessarily
			entered it into this application
		</description>
		<comment>
			This person is an alternate point of contact for the
			material
		</comment>
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="WIKI-ROLE-3" order="6"
		queued-flag="Y">
		<name>Approver</name>
		<description>
			Person responsible for approving or rejecting a content
			request
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="WIKI-ROLE-4" order="7"
		queued-flag="Y">
		<name>Initiator</name>
		<description>
			Person requesting the addition, modification or deletion of
			a piece of content
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="WIKI-ROLE-5" order="8"
		queued-flag="N">
		<name>Subscriber</name>
		<description>
			Person requesting a notification to be sent each time a
			piece of content is updated
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="WIKI-ROLE-9" order="9"
		queued-flag="N">
		<name>Content Remover</name>
		<description>
			Person who can remove content
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="CORE-ROLE-1" order="01"
		queued-flag="N">
		<name>Administrator</name>
		<description>
			Supports this site by ensuring its proper configuration,
			backup and execution
		</description>
		<comment>
			An administrator is in charge of various technical aspects
			of this site support. It includes monitoring and tuning the
			performance, backing up and restoring files, administrating
			the underlying database, installing and configuring the
			servers, installing and configuring this site software and
			controlling the version of this site
		</comment>
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-2" order="02"
		queued-flag="N">
		<name>Email From</name>
		<description>Sender of an email</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-3" order="03"
		queued-flag="N">
		<name>Email To</name>
		<description>Recipient of an email</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-4" order="04"
		queued-flag="N">
		<name>Email Cc</name>
		<description>Carbon copy recipient of an email</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-5" order="05"
		queued-flag="N">
		<name>Email Bcc</name>
		<description>
			Blind carbon copy recipient of an email
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-6" order="06"
		queued-flag="N">
		<name>Proxy Grantor</name>
		<description>
			User granting its transaction privileges to another user
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-7" order="07"
		queued-flag="N">
		<name>Proxy Grantee</name>
		<description>
			User receiving transaction privileges from another user
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-8" order="08"
		queued-flag="N">
		<name>Direct Manager</name>
		<description>User managing another person</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="CORE-ROLE-9" order="09"
		queued-flag="N">
		<name>Account General Administrator</name>
		<description>
			Role allowing the edition of accounts, but not the creation
			of accounts
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-10" order="10"
		queued-flag="N">
		<name>Company LDAP control</name>
		<description>
			Role associating a company with a LDAP control
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-11" order="11"
		queued-flag="N">
		<name>City LDAP control</name>
		<description>
			Role associating a city with a LDAP control
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-12" order="12"
		queued-flag="N">
		<name>State LDAP control</name>
		<description>
			Role associating a state with a LDAP control
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-13" order="13"
		queued-flag="N">
		<name>Country LDAP control</name>
		<description>
			Role associating a country with a LDAP control
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="Y" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-14" order="14"
		queued-flag="N">
		<name>Default LDAP control</name>
		<description>
			Role associating a building, a company, a city, a state or a
			country with a LDAP control
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="N" id="CORE-ROLE-15" order="15"
		queued-flag="N">
		<name>Account Template</name>
		<description>
			Role indicating that a user account is a template account
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="N" id="CORE-ROLE-16" order="16"
		queued-flag="N">
		<name>Active Directory Administration Recipient</name>
		<description>
			Role indicating that a user is the recipient of all emails
			notifying of a data update in Active Directory
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="CORE-ROLE-17" order="17"
		queued-flag="N">
		<name>Active Directory Room Administrator</name>
		<description>
			Role indicating that a user can update room numbers
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-18" order="18"
		queued-flag="N">
		<name>Account Photo Watermark Template</name>
		<description>
			Role indicating that a file is the watermark template for
			all photos
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="CORE-ROLE-19" order="19"
		queued-flag="N">
		<name>Administrative Proxy</name>
		<description>
			Role indicating that a user can use the administrative proxy
			feature
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="N"
		group-standalone-flag="N" id="CORE-ROLE-20" order="20"
		queued-flag="N">
		<name>Department Manager</name>
		<description>
			Role indicating that a user is the direct manager of another
			user
		</description>
		<comment />
	</role>
	<role enabled-flag="Y" file-standalone-flag="N"
		ldap-control-standalone-flag="N" account-standalone-flag="Y"
		group-standalone-flag="Y" id="CORE-ROLE-21" order="21"
		queued-flag="N">
		<name>Departments Administrator</name>
		<description>
			Role indicating that a user can manage the list of
			departments
		</description>
		<comment />
	</role>
