=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/servlets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: servlets.xsd,v 1.1 2006/07/08 21:15:56 tdanard Exp $ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="servlets">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="servlet"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="servlet">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="class"/>
      </xs:sequence>
      <xs:attribute name="default-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="enabled-flag" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:NCName"/>
  <xs:element name="class">
    <xs:complexType>
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/setups/servlets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version: $Id: servlets.xml,v 1.3 2006/07/17 02:23:36 tdanard Exp $ -->
<servlets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../schemas/servlets.xsd">
	<servlet default-flag="Y" enabled-flag="Y" id="CORE-SERV-1">
		<name>DynamicPageServlet</name>
		<class
			name="com.corendal.netapps.framework.core.servlets.DymamicDatabaseHTTPServlet" />
	</servlet>
	<servlet default-flag="N" enabled-flag="Y" id="CORE-SERV-2">
		<name>DailyCachedPageServlet</name>
		<class
			name="com.corendal.netapps.framework.core.servlets.DailyCachedDatabaseHTTPServlet" />
	</servlet>
	<servlet default-flag="N" enabled-flag="Y" id="CORE-SERV-3">
		<name>NoCachePageServlet</name>
		<class
			name="com.corendal.netapps.framework.core.servlets.NoCacheDatabaseHTTPServlet" />
	</servlet>
	<servlet default-flag="N" enabled-flag="Y" id="CORE-SERV-4">
		<name>MultipartPageServlet</name>
		<class
			name="com.corendal.netapps.framework.core.servlets.MultipartDatabaseHTTPServlet" />
	</servlet>
</servlets>
