=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/schemas/xmlsourcemapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="xmlsource-mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="class"/>
        <xs:element maxOccurs="unbounded" ref="query"/>
      </xs:sequence>
      <xs:attribute name="package" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="class">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
      </xs:sequence>
      <xs:attribute name="collection" use="required" type="xs:NCName"/>
      <xs:attribute name="entity" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="attribute" use="required" type="xs:NCName"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="query">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/xmlsource/defaultsetup/mappings/Role.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Role.xml,v 1.4 2007/12/18 19:25:39 tdanard Exp $ -->
<xmlsource-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/xmlsourcemapping.xsd"
	package="com.corendal.netapps.framework.core.readdatahandlers">
	<class name="DefaultRoleLoadHandler" collection="roles"
		entity="role">
		<id attribute="id" name="Id" type="string" />

	</class>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findByEnabledFlag">
		<![CDATA[for $result in /roles/role[@enabled-flag =
		:enabledFlag] order by $result/@order return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findEnabledByKeyword">
		<![CDATA[for $result in /roles/role[(name |= :keyword or
		description |= :keyword or comment |= :keyword) and
		(@enabled-flag = "Y")] order by $result/@order return $result]]>
	</query>
		<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findEnabledByAccountStandaloneFlag">
		<![CDATA[for $result in /roles/role[(@account-standalone-flag = :accountStandaloneFlag) and
		(@enabled-flag = "Y")] order by $result/@order return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findEnabledByGroupStandaloneFlag">
		<![CDATA[for $result in /roles/role[(@group-standalone-flag = :groupStandaloneFlag) and
		(@enabled-flag = "Y")] order by $result/@order return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findEnabledByLDAPControlStandaloneFlag">
		<![CDATA[for $result in /roles/role[(@ldap-control-standalone-flag = :ldapControlStandaloneFlag) and
		(@enabled-flag = "Y")] order by $result/@order return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractRole.findEnabledByFileStandaloneFlag">
		<![CDATA[for $result in /roles/role[(@file-standalone-flag = :fileStandaloneFlag) and
		(@enabled-flag = "Y")] order by $result/@order return $result]]>
	</query>
</xmlsource-mapping>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/xmlsource/defaultsetup/mappings/Entity.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Entity.xml,v 1.3 2006/07/17 02:23:37 tdanard Exp $ -->
<xmlsource-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/xmlsourcemapping.xsd"
	package="com.corendal.netapps.framework.core.readdatahandlers">
	<class name="DefaultEntityLoadHandler" collection="entities"
		entity="entity">
		<id attribute="id" name="Id" type="string" />

	</class>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractEntity.findByEnabledFlag">
		<![CDATA[for $result in /entities/entity[@enabled-flag = :enabledFlag]
		return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractEntity.findEnabledBySearchPriority">
		<![CDATA[for $result in /entities/entity[not(@search-priority = 0) and
		@enabled-flag = "Y"] order by $result/@search-priority return
		$result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractEntity.findEnabledByParentEntityPrimaryKey">
		<![CDATA[for $result in /entities/entity[@parent-entity-id =
		:parentEntityId and @enabled-flag = "Y"] order by $result/@child-priority return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractEntity.findEnabledByIndexedFlag">
		<![CDATA[for $result in /entities/entity[@indexed-flag = :indexedFlag and
		@enabled-flag = "Y"] return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractEntity.findEnabledByKeyword">
		<![CDATA[for $result in /entities/entity[(zero-name |= :keyword or
		singular-name |= :keyword or plural-name |= :keyword or
		description |= :keyword or comment |= :keyword) and
		(@indexed-flag = "Y") and (@enabled-flag = "Y")] return $result]]>
	</query>
</xmlsource-mapping>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/xmlsource/defaultsetup/mappings/Block.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Block.xml,v 1.4 2006/11/07 01:42:07 tdanard Exp $ -->
<xmlsource-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/xmlsourcemapping.xsd"
	package="com.corendal.netapps.framework.core.readdatahandlers">
	<class name="DefaultBlockLoadHandler" collection="blocks"
		entity="block">
		<id attribute="id" name="Id" type="string" />

	</class>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractBlock.findByEnabledFlag">
		<![CDATA[for $result in /blocks/block[@enabled-flag = :enabledFlag]
		return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractBlock.findEnabledByKeyword">
		<![CDATA[for $result in /blocks/block[(name |= :keyword or description |=
		:keyword or comment |= :keyword) and (@indexed-flag = "Y") and
		(@enabled-flag = "Y")] return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPage.findEnabledByBlockPrimaryKey">
		<![CDATA[for $result in /blocks/block[@id = :blockId] return
		$result/class/pagesblock-pages/pagesblock-page]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractMessage.findEnabledByBlockPrimaryKey">
		<![CDATA[for $result in /blocks/block[@id = :blockId] return
		$result/class/messagesblock-messages/messagesblock-message]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractBlockPageXref.load">
		<![CDATA[for $result in /blocks/block[@id = :blockId] return
		$result/class/pagesblock-pages/pagesblock-page[@page-id = :pageId]]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractBlockPageXref.findEnabledByBlockPrimaryKey">
		<![CDATA[for $result in /blocks/block[@id = :blockId] return
		$result/class/pagesblock-pages/pagesblock-page]]>
	</query>
</xmlsource-mapping>

=== j123kaishichufa/RS17_corendalwiki302/corendal-wiki-3.0.2/wiki/WEB-INF/configs/wikidevconfig/datasources/xmlsource/defaultsetup/mappings/Page.xml
<?xml version='1.0' encoding='utf-8'?>
<!-- Version: $Id: Page.xml,v 1.3 2006/07/17 02:23:37 tdanard Exp $ -->
<xmlsource-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../../../schemas/xmlsourcemapping.xsd"
	package="com.corendal.netapps.framework.core.readdatahandlers">
	<class name="DefaultPageLoadHandler" collection="pages"
		entity="page">
		<id attribute="id" name="Id" type="string" />

	</class>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractBlock.findEnabledByPagePrimaryKeyAndType">
		<![CDATA[for $result in /pages/page[@id = :pageId] return
		$result/class/blockspage-blocks/blockspage-block[@type = :type]]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPage.findByEnabledFlag">
		<![CDATA[for $result in /pages/page[@enabled-flag = :enabledFlag] return
		$result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPage.findEnabledByKeyword">
		<![CDATA[for $result in /pages/page[(name |= :keyword or description |=
		:keyword or comment |= :keyword) and (@indexed-flag = "Y") and
		(@enabled-flag = "Y")] return $result]]>
	</query>
    <query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPage.findEnabledByIndexedFlag">
		<![CDATA[for $result in /pages/page[@indexed-flag = :indexedFlag and
		@enabled-flag = "Y"] return $result]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPageBlockXref.load">
		<![CDATA[for $result in /pages/page[@id = :pageId] return
		$result/class/blockspage-blocks/blockspage-block[@block-id = :blockId]]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractPageBlockXref.findEnabledByPagePrimaryKey">
		<![CDATA[for $result in /pages/page[@id = :pageId] return
		$result/class/blockspage-blocks/blockspage-block]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractURL.load">
		<![CDATA[for $result in /pages/page[@id = :pageId] return
		$result/urls/url[@directory = :directory and @base = :base]]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractURL.findEnabledByPagePrimaryKey">
		<![CDATA[for $result in /pages/page[@id = :pageId] return
		$result/urls/url]]>
	</query>
	<query
		name="com.corendal.netapps.framework.core.readdatabeans.AbstractURL.findEnabledByDirectoryAndBase">
		<![CDATA[for $result in /pages/page
		where $result/urls/url[@directory = :directory and @base = :base]
		return $result]]>
	</query>
</xmlsource-mapping>
